#!/usr/bin/env bash
# Installs Nginx.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
printf "Ceci n'est pas une page\n" > /usr/share/nginx/html/404.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.youtube.com permanent;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
service nginx start
